exclude_patterns:
  - 'dev'
  - 'docs'
  - 'examples'
  - 'tests'
  - 'jest.config.ts'
  - 'jest.integration.js'
  - '.*'
  - 'packages/@roots/*/templates'
  - 'packages/@roots/*/src/docs'
plugins:
  eslint:
    enabled: true
  